name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - id: First step
        name: First step
        run: echo " this is the first github action "

      - id: second step
        name: checking out the repository
        uses: actions/checkout@v2

      - id: third step
        name: Listing all available file
        run: ls ${{ github.workspace }} 
        run: echo "🍏 This job's status is ${{ job.status }}."
     
