name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo " this is the first github action "
      - name: checking out the repository
        uses: actions/checkout@v2
        run: ls ${{ github.workspace }} 
      - run: echo "🍏 This job's status is ${{ job.status }}."
     
