name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - id: "first"
        name: First step
        run: echo " this is the first github action "

      - id: "second"
        name: checking out the repository
        uses: actions/checkout@v2

      - id: "third"
        name: Listing all available file
        run: ls ${{ github.workspace }}

      - name: Make .env file
        uses:  SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: "123456abcdef"
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY}}
          some_other_variable: foobar
          directory: football_game
          file_name: .env
          fail_on_empty: false

      - name: Display .env content
        run: cat football_game/.env

      - name: Print our secret
        run: echo " ${{ secrets.SECRET_KEY }}"

      - name: set up secret file
        env: 
          PASSWORD: ${{ secrets.SECRET_KEY }}
        run: echo $PASSWORD

      - name: Generate yaml file
        uses: mshick/fast-envsubst@v1
        with:
          env-file: football_game/.env
          in-file: app.yaml.template
          out-file: app.yaml

      - name: "Final execution"
        run: echo "🍏 This job's status is ${{ job.status }}."
     
